sudo: false
language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - tip

install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - go get -v -d -t ./...

script:
  - go test -v -race ./...
  - gometalinter --enable=gofmt,goimports ./...